'use client'

import dynamic from 'next/dynamic'
import Link from 'next/link'
import { useState } from 'react'
import { AppNavbar } from '@/components/app-navbar'
import { ArrowRight, BrainCircuit, Check, Code2, Cpu, GitBranch, Layers3, Network, Play, Route, Workflow } from 'lucide-react'

const RouteMap = dynamic(() => import('@/components/route-map').then((module) => module.RouteMap), { ssr: false, loading: () => <div className="real-map-shell map-loading">Loading live map…</div> })

type PageKey = 'network-model' | 'formulation' | 'algorithms' | 'platform' | 'demonstration'
const nav: { href: string; label: string }[] = [{ href: '/', label: 'Overview' }, { href: '/network-model', label: 'Network Model' }, { href: '/formulation', label: 'Formulation' }, { href: '/algorithms', label: 'Algorithms' }, { href: '/platform', label: 'Platform' }, { href: '/demonstration', label: 'Demonstration' }]
const pageData: Record<PageKey, { eyebrow: string; title: string; intro: string }> = {
  'network-model': { eyebrow: '01 / NETWORK MODEL', title: 'Graph-based network model', intro: 'A road network becomes a weighted graph: intersections are nodes, road segments are edges, and traffic updates the cost of every movement.' },
  formulation: { eyebrow: '02 / FORMULATION', title: 'Mathematical formulation', intro: 'The engine minimizes a weighted routing objective while preserving network flow, capacity, and time-window constraints.' },
  algorithms: { eyebrow: '03 / ALGORITHMS', title: 'Four search strategies', intro: 'Each solver explores the same network with a different optimization strategy. Compare their route impact without changing the scenario.' },
  platform: { eyebrow: '04 / PLATFORM', title: 'Evaluation platform', intro: 'A compact pipeline turns traffic observations into measurable route decisions and an auditable result.' },
  demonstration: { eyebrow: '05 / DEMONSTRATION', title: 'Live route demonstration', intro: 'Run the benchmark scenario on the same geographic network used by the overview dashboard.' },
}

export function TechnicalSectionPage({ page }: { page: PageKey }) {
  const [running, setRunning] = useState(false)
  const data = pageData[page]
  return <main className="technical-page">
    <AppNavbar />
    <div className="technical-layout"><aside className="technical-sidebar"><div className="eyebrow"><Network size={14} /> SYSTEM NOTES</div><h1>Route optimization<br /><span>from model to result.</span></h1><p>Technical reference for the Algo Route benchmark.</p><nav className="technical-sections" aria-label="Documentation pages">{nav.slice(1).map(item => <Link className={item.href === `/${page}` ? 'active' : ''} key={item.href} href={item.href}>{item.label}<ArrowRight size={14} /></Link>)}</nav><Link href="/" className="back-dashboard"><ArrowRight size={15} /> Back to overview</Link></aside>
      <section className="technical-content"><div className="tech-hero"><div className="eyebrow">{data.eyebrow} <span>LIVE</span></div><h2>{data.title}</h2><p>{data.intro}</p></div>
        {page === 'network-model' && <><section className="tech-grid"><article className="tech-panel wide-panel"><div className="panel-topline"><span className="section-number">A</span><div><div className="eyebrow">GEOGRAPHIC GRAPH</div><h3>Roads, intersections, traffic</h3></div></div><RouteMap algorithm="QPSO" traffic="Dynamic Traffic" /><p className="panel-copy">Nodes represent intersections or depots. Edges represent connected roads. Their weights combine distance, travel time, operating cost, and congestion.</p></article><article className="tech-panel compact-panel"><span className="panel-icon"><Network size={18} /></span><div className="eyebrow">WEIGHT VECTOR</div><h3>Dynamic edge costs</h3><ul className="signal-list"><li><span className="signal-dot blue" /> Distance <strong>km</strong></li><li><span className="signal-dot green" /> Travel time <strong>min</strong></li><li><span className="signal-dot orange" /> Congestion <strong>0–1</strong></li><li><span className="signal-dot purple" /> Cost <strong>USD</strong></li></ul></article></section></>}
        {page === 'formulation' && <section className="tech-panel formulation-panel"><div className="panel-topline"><span className="section-number">J</span><div><div className="eyebrow">OBJECTIVE FUNCTION</div><h3>Minimize routing cost</h3></div><span className="formula-status"><Check size={13} /> constrained</span></div><div className="formula-layout"><div className="formula-block"><span className="formula-label">OBJECTIVE</span><div className="formula-display">min <span>J(R)</span> = <span>α</span> · D(R) + <span>β</span> · T(R) + <span>γ</span> · C(R)</div><p>Distance, travel time, and operating cost are weighted for the active scenario.</p></div><div className="constraint-block"><span className="formula-label">CONSTRAINTS</span><div className="constraint-row"><span>Flow continuity</span><code>Σxᵢⱼ − Σxⱼₖ = bⱼ</code></div><div className="constraint-row"><span>Capacity</span><code>load ≤ capacity</code></div><div className="constraint-row"><span>Time window</span><code>tᵢ ≤ arrivalᵢ ≤ t̄ᵢ</code></div></div></div></section>}
        {page === 'algorithms' && <section className="algorithm-table">{[['QPSO','Quantum-inspired global search','24.35 km'],['GA','Crossover and mutation','26.18 km'],['ALNS','Destroy and repair neighborhoods','26.92 km'],['PSO','Fast swarm convergence','27.43 km']].map(([name, idea, result], i) => <article className="algorithm-row" key={name}><span className="algorithm-rank rank-blue">0{i + 1}</span><div className="algorithm-name"><strong>{name}</strong><span>{idea}</span></div><div className="algorithm-tags"><span>Dynamic traffic</span><span>Route search</span></div><div className="algorithm-result"><strong>{result}</strong><span>benchmark route</span></div></article>)}</section>}
        {page === 'platform' && <section className="tech-panel architecture-panel"><div className="panel-topline"><span className="section-number">→</span><div><div className="eyebrow">SYSTEM PIPELINE</div><h3>From traffic to metrics</h3></div></div><div className="pipeline"><div><Network size={16} /><span>Network<br />traffic</span></div><i /><div><GitBranch size={16} /><span>Graph<br />model</span></div><i /><div><BrainCircuit size={16} /><span>Optimization<br />engine</span></div><i /><div><Workflow size={16} /><span>Route<br />evaluation</span></div><i /><div><Layers3 size={16} /><span>Map<br />metrics</span></div></div></section>}
        {page === 'demonstration' && <section className="demo-panel"><div className="demo-copy"><div className="eyebrow">QPSO / DYNAMIC TRAFFIC</div><h3>Optimized route replay</h3><p>Traffic conditions are weighted on the road network before the route is evaluated.</p><button type="button" className="primary-tech-button" onClick={() => { setRunning(true); window.setTimeout(() => setRunning(false), 3000) }}><Play size={15} /> {running ? 'Optimizing route…' : 'Run simulation'}</button></div><div className={`demo-visual ${running ? 'is-running' : ''}`}><RouteMap algorithm="QPSO" traffic="Dynamic Traffic" /></div></section>}
      </section></div></main>
}
